package mylas.com.erp.demo;
// Generated 9 May, 2018 2:21:04 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpDetails generated by hbm2java
 */
@Entity
@Table(name = "emp_details", schema = "krishna", catalog = "mylasfyt_krishna")
public class EmpDetails implements java.io.Serializable {

	private Integer empid;
	private String firstName;
	private String lastName;
	private String email;
	private String address1;
	private String address2;
	private String city;
	private String state1;
	private String pin;
	private Integer mobile;
	private Integer phone;
	private Integer panCard;
	private Integer aadharCard;
	private Date hireDate;
	private Date termDate;
	private String termReason;
	private Date bdate;
	private String marital;
	private String gender;
	private String title;

	public EmpDetails() {
	}

	public EmpDetails(String firstName, String lastName, String email, String address1, String address2, String city,
			String state1, String pin, Integer mobile, Integer phone, Integer panCard, Integer aadharCard,
			Date hireDate, Date termDate, String termReason, Date bdate, String marital, String gender, String title) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state1 = state1;
		this.pin = pin;
		this.mobile = mobile;
		this.phone = phone;
		this.panCard = panCard;
		this.aadharCard = aadharCard;
		this.hireDate = hireDate;
		this.termDate = termDate;
		this.termReason = termReason;
		this.bdate = bdate;
		this.marital = marital;
		this.gender = gender;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Empid", unique = true, nullable = false)
	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	@Column(name = "FirstName", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Address1", length = 50)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2", length = 50)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "City", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state1", length = 50)
	public String getState1() {
		return this.state1;
	}

	public void setState1(String state1) {
		this.state1 = state1;
	}

	@Column(name = "Pin", length = 6)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "Mobile")
	public Integer getMobile() {
		return this.mobile;
	}

	public void setMobile(Integer mobile) {
		this.mobile = mobile;
	}

	@Column(name = "Phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Column(name = "PanCard")
	public Integer getPanCard() {
		return this.panCard;
	}

	public void setPanCard(Integer panCard) {
		this.panCard = panCard;
	}

	@Column(name = "AadharCard")
	public Integer getAadharCard() {
		return this.aadharCard;
	}

	public void setAadharCard(Integer aadharCard) {
		this.aadharCard = aadharCard;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HireDate", length = 10)
	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TermDate", length = 10)
	public Date getTermDate() {
		return this.termDate;
	}

	public void setTermDate(Date termDate) {
		this.termDate = termDate;
	}

	@Column(name = "TermReason")
	public String getTermReason() {
		return this.termReason;
	}

	public void setTermReason(String termReason) {
		this.termReason = termReason;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Bdate", length = 10)
	public Date getBdate() {
		return this.bdate;
	}

	public void setBdate(Date bdate) {
		this.bdate = bdate;
	}

	@Column(name = "Marital", length = 10)
	public String getMarital() {
		return this.marital;
	}

	public void setMarital(String marital) {
		this.marital = marital;
	}

	@Column(name = "Gender", length = 6)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "Title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
