package mylas.com.erp.demo;
// Generated 13 May, 2018 10:58:13 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.stereotype.Repository;

/**
 * EmpDetails generated by hbm2java
 */
@Repository
@Entity
@Table(name = "emp_details", schema = "krishna", catalog = "mylasfyt_krishna", uniqueConstraints = {
		@UniqueConstraint(columnNames = "uname"), @UniqueConstraint(columnNames = "eid") })
public class EmpDetails implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String lname;
	private String uname;
	private String email;
	private String pswd;
	private String cpswd;
	private String eid;
	private Date jdate;
	private Integer phone;
	private String compName;
	private String designation;
	private boolean role;
	private boolean loginStatus;
	private Boolean usrmanrole;

	public EmpDetails() {
	}

	public EmpDetails(String uname, String eid, boolean role, boolean loginStatus) {
		this.uname = uname;
		this.eid = eid;
		this.role = role;
		this.loginStatus = loginStatus;
	}

	public EmpDetails(String fname, String lname, String uname, String email, String pswd, String cpswd, String eid,
			Date jdate, Integer phone, String compName, String designation, boolean role, boolean loginStatus,
			Boolean usrmanrole) {
		this.fname = fname;
		this.lname = lname;
		this.uname = uname;
		this.email = email;
		this.pswd = pswd;
		this.cpswd = cpswd;
		this.eid = eid;
		this.jdate = jdate;
		this.phone = phone;
		this.compName = compName;
		this.designation = designation;
		this.role = role;
		this.loginStatus = loginStatus;
		this.usrmanrole = usrmanrole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fname", length = 50)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "lname", length = 50)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "uname", unique = true, nullable = false, length = 50)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "pswd", length = 50)
	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	@Column(name = "cpswd", length = 50)
	public String getCpswd() {
		return this.cpswd;
	}

	public void setCpswd(String cpswd) {
		this.cpswd = cpswd;
	}

	@Column(name = "eid", unique = true, nullable = false, length = 50)
	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jdate", length = 10)
	public Date getJdate() {
		return this.jdate;
	}

	public void setJdate(Date jdate) {
		this.jdate = jdate;
	}

	@Column(name = "phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Column(name = "compName", length = 50)
	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	@Column(name = "designation", length = 50)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "role", nullable = false)
	public boolean isRole() {
		return this.role;
	}

	public void setRole(boolean role) {
		this.role = role;
	}

	@Column(name = "login_status", nullable = false)
	public boolean isLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(boolean loginStatus) {
		this.loginStatus = loginStatus;
	}

	@Column(name = "usrmanrole")
	public Boolean getUsrmanrole() {
		return this.usrmanrole;
	}

	public void setUsrmanrole(Boolean usrmanrole) {
		this.usrmanrole = usrmanrole;
	}

}
