package mylas.com.erp.demo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.stereotype.Repository;

/**
 * TblDesignation generated by hbm2java
 */
@Repository
@Entity
@Table(name = "tbl_Designation", schema = "krishna", catalog = "mylasfyt_krishna")
public class TblDesignation implements java.io.Serializable {

	private Integer designationId;
	private String designation;

	public TblDesignation() {
	}

	public TblDesignation(String designation) {
		this.designation = designation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DesignationId", unique = true, nullable = false)
	public Integer getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(Integer designationId) {
		this.designationId = designationId;
	}

	@Column(name = "Designation", length = 50)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

}
