package mylas.com.erp.demo;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblEmpAttendanceNewId generated by hbm2java
 */
@Embeddable
public class TblEmpAttendanceNewId implements java.io.Serializable {

	private String managerid;
	private String empid;
	private String month;
	private Integer year;
	private Boolean day1;
	private Boolean day2;
	private Boolean day3;
	private Boolean day4;
	private Boolean day5;
	private Boolean day6;
	private Boolean day7;
	private Boolean day8;
	private Boolean day9;
	private Boolean day10;
	private Boolean day11;
	private Boolean day12;
	private Boolean day13;
	private Boolean day14;
	private Boolean day15;
	private Boolean day16;
	private Boolean day17;
	private Boolean day18;
	private Boolean day19;
	private Boolean day20;
	private Boolean day21;
	private Boolean day22;
	private Boolean day23;
	private Boolean day24;
	private Boolean day25;
	private Boolean day26;
	private Boolean day27;
	private Boolean day28;
	private Boolean day29;
	private Boolean day30;
	private Boolean day31;
	private Boolean statas;
	private String reasion;

	public TblEmpAttendanceNewId() {
	}

	public TblEmpAttendanceNewId(String managerid, String empid, String month, Integer year, Boolean day1, Boolean day2,
			Boolean day3, Boolean day4, Boolean day5, Boolean day6, Boolean day7, Boolean day8, Boolean day9,
			Boolean day10, Boolean day11, Boolean day12, Boolean day13, Boolean day14, Boolean day15, Boolean day16,
			Boolean day17, Boolean day18, Boolean day19, Boolean day20, Boolean day21, Boolean day22, Boolean day23,
			Boolean day24, Boolean day25, Boolean day26, Boolean day27, Boolean day28, Boolean day29, Boolean day30,
			Boolean day31, Boolean statas, String reasion) {
		this.managerid = managerid;
		this.empid = empid;
		this.month = month;
		this.year = year;
		this.day1 = day1;
		this.day2 = day2;
		this.day3 = day3;
		this.day4 = day4;
		this.day5 = day5;
		this.day6 = day6;
		this.day7 = day7;
		this.day8 = day8;
		this.day9 = day9;
		this.day10 = day10;
		this.day11 = day11;
		this.day12 = day12;
		this.day13 = day13;
		this.day14 = day14;
		this.day15 = day15;
		this.day16 = day16;
		this.day17 = day17;
		this.day18 = day18;
		this.day19 = day19;
		this.day20 = day20;
		this.day21 = day21;
		this.day22 = day22;
		this.day23 = day23;
		this.day24 = day24;
		this.day25 = day25;
		this.day26 = day26;
		this.day27 = day27;
		this.day28 = day28;
		this.day29 = day29;
		this.day30 = day30;
		this.day31 = day31;
		this.statas = statas;
		this.reasion = reasion;
	}

	@Column(name = "managerid", length = 1)
	public String getManagerid() {
		return this.managerid;
	}

	public void setManagerid(String managerid) {
		this.managerid = managerid;
	}

	@Column(name = "empid", length = 1)
	public String getEmpid() {
		return this.empid;
	}

	public void setEmpid(String empid) {
		this.empid = empid;
	}

	@Column(name = "month", length = 1)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "day1")
	public Boolean getDay1() {
		return this.day1;
	}

	public void setDay1(Boolean day1) {
		this.day1 = day1;
	}

	@Column(name = "day2")
	public Boolean getDay2() {
		return this.day2;
	}

	public void setDay2(Boolean day2) {
		this.day2 = day2;
	}

	@Column(name = "day3")
	public Boolean getDay3() {
		return this.day3;
	}

	public void setDay3(Boolean day3) {
		this.day3 = day3;
	}

	@Column(name = "day4")
	public Boolean getDay4() {
		return this.day4;
	}

	public void setDay4(Boolean day4) {
		this.day4 = day4;
	}

	@Column(name = "day5")
	public Boolean getDay5() {
		return this.day5;
	}

	public void setDay5(Boolean day5) {
		this.day5 = day5;
	}

	@Column(name = "day6")
	public Boolean getDay6() {
		return this.day6;
	}

	public void setDay6(Boolean day6) {
		this.day6 = day6;
	}

	@Column(name = "day7")
	public Boolean getDay7() {
		return this.day7;
	}

	public void setDay7(Boolean day7) {
		this.day7 = day7;
	}

	@Column(name = "day8")
	public Boolean getDay8() {
		return this.day8;
	}

	public void setDay8(Boolean day8) {
		this.day8 = day8;
	}

	@Column(name = "day9")
	public Boolean getDay9() {
		return this.day9;
	}

	public void setDay9(Boolean day9) {
		this.day9 = day9;
	}

	@Column(name = "day10")
	public Boolean getDay10() {
		return this.day10;
	}

	public void setDay10(Boolean day10) {
		this.day10 = day10;
	}

	@Column(name = "day11")
	public Boolean getDay11() {
		return this.day11;
	}

	public void setDay11(Boolean day11) {
		this.day11 = day11;
	}

	@Column(name = "day12")
	public Boolean getDay12() {
		return this.day12;
	}

	public void setDay12(Boolean day12) {
		this.day12 = day12;
	}

	@Column(name = "day13")
	public Boolean getDay13() {
		return this.day13;
	}

	public void setDay13(Boolean day13) {
		this.day13 = day13;
	}

	@Column(name = "day14")
	public Boolean getDay14() {
		return this.day14;
	}

	public void setDay14(Boolean day14) {
		this.day14 = day14;
	}

	@Column(name = "day15")
	public Boolean getDay15() {
		return this.day15;
	}

	public void setDay15(Boolean day15) {
		this.day15 = day15;
	}

	@Column(name = "day16")
	public Boolean getDay16() {
		return this.day16;
	}

	public void setDay16(Boolean day16) {
		this.day16 = day16;
	}

	@Column(name = "day17")
	public Boolean getDay17() {
		return this.day17;
	}

	public void setDay17(Boolean day17) {
		this.day17 = day17;
	}

	@Column(name = "day18")
	public Boolean getDay18() {
		return this.day18;
	}

	public void setDay18(Boolean day18) {
		this.day18 = day18;
	}

	@Column(name = "day19")
	public Boolean getDay19() {
		return this.day19;
	}

	public void setDay19(Boolean day19) {
		this.day19 = day19;
	}

	@Column(name = "day20")
	public Boolean getDay20() {
		return this.day20;
	}

	public void setDay20(Boolean day20) {
		this.day20 = day20;
	}

	@Column(name = "day21")
	public Boolean getDay21() {
		return this.day21;
	}

	public void setDay21(Boolean day21) {
		this.day21 = day21;
	}

	@Column(name = "day22")
	public Boolean getDay22() {
		return this.day22;
	}

	public void setDay22(Boolean day22) {
		this.day22 = day22;
	}

	@Column(name = "day23")
	public Boolean getDay23() {
		return this.day23;
	}

	public void setDay23(Boolean day23) {
		this.day23 = day23;
	}

	@Column(name = "day24")
	public Boolean getDay24() {
		return this.day24;
	}

	public void setDay24(Boolean day24) {
		this.day24 = day24;
	}

	@Column(name = "day25")
	public Boolean getDay25() {
		return this.day25;
	}

	public void setDay25(Boolean day25) {
		this.day25 = day25;
	}

	@Column(name = "day26")
	public Boolean getDay26() {
		return this.day26;
	}

	public void setDay26(Boolean day26) {
		this.day26 = day26;
	}

	@Column(name = "day27")
	public Boolean getDay27() {
		return this.day27;
	}

	public void setDay27(Boolean day27) {
		this.day27 = day27;
	}

	@Column(name = "day28")
	public Boolean getDay28() {
		return this.day28;
	}

	public void setDay28(Boolean day28) {
		this.day28 = day28;
	}

	@Column(name = "day29")
	public Boolean getDay29() {
		return this.day29;
	}

	public void setDay29(Boolean day29) {
		this.day29 = day29;
	}

	@Column(name = "day30")
	public Boolean getDay30() {
		return this.day30;
	}

	public void setDay30(Boolean day30) {
		this.day30 = day30;
	}

	@Column(name = "day31")
	public Boolean getDay31() {
		return this.day31;
	}

	public void setDay31(Boolean day31) {
		this.day31 = day31;
	}

	@Column(name = "statas")
	public Boolean getStatas() {
		return this.statas;
	}

	public void setStatas(Boolean statas) {
		this.statas = statas;
	}

	@Column(name = "reasion", length = 1)
	public String getReasion() {
		return this.reasion;
	}

	public void setReasion(String reasion) {
		this.reasion = reasion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblEmpAttendanceNewId))
			return false;
		TblEmpAttendanceNewId castOther = (TblEmpAttendanceNewId) other;

		return ((this.getManagerid() == castOther.getManagerid()) || (this.getManagerid() != null
				&& castOther.getManagerid() != null && this.getManagerid().equals(castOther.getManagerid())))
				&& ((this.getEmpid() == castOther.getEmpid()) || (this.getEmpid() != null
						&& castOther.getEmpid() != null && this.getEmpid().equals(castOther.getEmpid())))
				&& ((this.getMonth() == castOther.getMonth()) || (this.getMonth() != null
						&& castOther.getMonth() != null && this.getMonth().equals(castOther.getMonth())))
				&& ((this.getYear() == castOther.getYear()) || (this.getYear() != null && castOther.getYear() != null
						&& this.getYear().equals(castOther.getYear())))
				&& ((this.getDay1() == castOther.getDay1()) || (this.getDay1() != null && castOther.getDay1() != null
						&& this.getDay1().equals(castOther.getDay1())))
				&& ((this.getDay2() == castOther.getDay2()) || (this.getDay2() != null && castOther.getDay2() != null
						&& this.getDay2().equals(castOther.getDay2())))
				&& ((this.getDay3() == castOther.getDay3()) || (this.getDay3() != null && castOther.getDay3() != null
						&& this.getDay3().equals(castOther.getDay3())))
				&& ((this.getDay4() == castOther.getDay4()) || (this.getDay4() != null && castOther.getDay4() != null
						&& this.getDay4().equals(castOther.getDay4())))
				&& ((this.getDay5() == castOther.getDay5()) || (this.getDay5() != null && castOther.getDay5() != null
						&& this.getDay5().equals(castOther.getDay5())))
				&& ((this.getDay6() == castOther.getDay6()) || (this.getDay6() != null && castOther.getDay6() != null
						&& this.getDay6().equals(castOther.getDay6())))
				&& ((this.getDay7() == castOther.getDay7()) || (this.getDay7() != null && castOther.getDay7() != null
						&& this.getDay7().equals(castOther.getDay7())))
				&& ((this.getDay8() == castOther.getDay8()) || (this.getDay8() != null && castOther.getDay8() != null
						&& this.getDay8().equals(castOther.getDay8())))
				&& ((this.getDay9() == castOther.getDay9()) || (this.getDay9() != null && castOther.getDay9() != null
						&& this.getDay9().equals(castOther.getDay9())))
				&& ((this.getDay10() == castOther.getDay10()) || (this.getDay10() != null
						&& castOther.getDay10() != null && this.getDay10().equals(castOther.getDay10())))
				&& ((this.getDay11() == castOther.getDay11()) || (this.getDay11() != null
						&& castOther.getDay11() != null && this.getDay11().equals(castOther.getDay11())))
				&& ((this.getDay12() == castOther.getDay12()) || (this.getDay12() != null
						&& castOther.getDay12() != null && this.getDay12().equals(castOther.getDay12())))
				&& ((this.getDay13() == castOther.getDay13()) || (this.getDay13() != null
						&& castOther.getDay13() != null && this.getDay13().equals(castOther.getDay13())))
				&& ((this.getDay14() == castOther.getDay14()) || (this.getDay14() != null
						&& castOther.getDay14() != null && this.getDay14().equals(castOther.getDay14())))
				&& ((this.getDay15() == castOther.getDay15()) || (this.getDay15() != null
						&& castOther.getDay15() != null && this.getDay15().equals(castOther.getDay15())))
				&& ((this.getDay16() == castOther.getDay16()) || (this.getDay16() != null
						&& castOther.getDay16() != null && this.getDay16().equals(castOther.getDay16())))
				&& ((this.getDay17() == castOther.getDay17()) || (this.getDay17() != null
						&& castOther.getDay17() != null && this.getDay17().equals(castOther.getDay17())))
				&& ((this.getDay18() == castOther.getDay18()) || (this.getDay18() != null
						&& castOther.getDay18() != null && this.getDay18().equals(castOther.getDay18())))
				&& ((this.getDay19() == castOther.getDay19()) || (this.getDay19() != null
						&& castOther.getDay19() != null && this.getDay19().equals(castOther.getDay19())))
				&& ((this.getDay20() == castOther.getDay20()) || (this.getDay20() != null
						&& castOther.getDay20() != null && this.getDay20().equals(castOther.getDay20())))
				&& ((this.getDay21() == castOther.getDay21()) || (this.getDay21() != null
						&& castOther.getDay21() != null && this.getDay21().equals(castOther.getDay21())))
				&& ((this.getDay22() == castOther.getDay22()) || (this.getDay22() != null
						&& castOther.getDay22() != null && this.getDay22().equals(castOther.getDay22())))
				&& ((this.getDay23() == castOther.getDay23()) || (this.getDay23() != null
						&& castOther.getDay23() != null && this.getDay23().equals(castOther.getDay23())))
				&& ((this.getDay24() == castOther.getDay24()) || (this.getDay24() != null
						&& castOther.getDay24() != null && this.getDay24().equals(castOther.getDay24())))
				&& ((this.getDay25() == castOther.getDay25()) || (this.getDay25() != null
						&& castOther.getDay25() != null && this.getDay25().equals(castOther.getDay25())))
				&& ((this.getDay26() == castOther.getDay26()) || (this.getDay26() != null
						&& castOther.getDay26() != null && this.getDay26().equals(castOther.getDay26())))
				&& ((this.getDay27() == castOther.getDay27()) || (this.getDay27() != null
						&& castOther.getDay27() != null && this.getDay27().equals(castOther.getDay27())))
				&& ((this.getDay28() == castOther.getDay28()) || (this.getDay28() != null
						&& castOther.getDay28() != null && this.getDay28().equals(castOther.getDay28())))
				&& ((this.getDay29() == castOther.getDay29()) || (this.getDay29() != null
						&& castOther.getDay29() != null && this.getDay29().equals(castOther.getDay29())))
				&& ((this.getDay30() == castOther.getDay30()) || (this.getDay30() != null
						&& castOther.getDay30() != null && this.getDay30().equals(castOther.getDay30())))
				&& ((this.getDay31() == castOther.getDay31()) || (this.getDay31() != null
						&& castOther.getDay31() != null && this.getDay31().equals(castOther.getDay31())))
				&& ((this.getStatas() == castOther.getStatas()) || (this.getStatas() != null
						&& castOther.getStatas() != null && this.getStatas().equals(castOther.getStatas())))
				&& ((this.getReasion() == castOther.getReasion()) || (this.getReasion() != null
						&& castOther.getReasion() != null && this.getReasion().equals(castOther.getReasion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getManagerid() == null ? 0 : this.getManagerid().hashCode());
		result = 37 * result + (getEmpid() == null ? 0 : this.getEmpid().hashCode());
		result = 37 * result + (getMonth() == null ? 0 : this.getMonth().hashCode());
		result = 37 * result + (getYear() == null ? 0 : this.getYear().hashCode());
		result = 37 * result + (getDay1() == null ? 0 : this.getDay1().hashCode());
		result = 37 * result + (getDay2() == null ? 0 : this.getDay2().hashCode());
		result = 37 * result + (getDay3() == null ? 0 : this.getDay3().hashCode());
		result = 37 * result + (getDay4() == null ? 0 : this.getDay4().hashCode());
		result = 37 * result + (getDay5() == null ? 0 : this.getDay5().hashCode());
		result = 37 * result + (getDay6() == null ? 0 : this.getDay6().hashCode());
		result = 37 * result + (getDay7() == null ? 0 : this.getDay7().hashCode());
		result = 37 * result + (getDay8() == null ? 0 : this.getDay8().hashCode());
		result = 37 * result + (getDay9() == null ? 0 : this.getDay9().hashCode());
		result = 37 * result + (getDay10() == null ? 0 : this.getDay10().hashCode());
		result = 37 * result + (getDay11() == null ? 0 : this.getDay11().hashCode());
		result = 37 * result + (getDay12() == null ? 0 : this.getDay12().hashCode());
		result = 37 * result + (getDay13() == null ? 0 : this.getDay13().hashCode());
		result = 37 * result + (getDay14() == null ? 0 : this.getDay14().hashCode());
		result = 37 * result + (getDay15() == null ? 0 : this.getDay15().hashCode());
		result = 37 * result + (getDay16() == null ? 0 : this.getDay16().hashCode());
		result = 37 * result + (getDay17() == null ? 0 : this.getDay17().hashCode());
		result = 37 * result + (getDay18() == null ? 0 : this.getDay18().hashCode());
		result = 37 * result + (getDay19() == null ? 0 : this.getDay19().hashCode());
		result = 37 * result + (getDay20() == null ? 0 : this.getDay20().hashCode());
		result = 37 * result + (getDay21() == null ? 0 : this.getDay21().hashCode());
		result = 37 * result + (getDay22() == null ? 0 : this.getDay22().hashCode());
		result = 37 * result + (getDay23() == null ? 0 : this.getDay23().hashCode());
		result = 37 * result + (getDay24() == null ? 0 : this.getDay24().hashCode());
		result = 37 * result + (getDay25() == null ? 0 : this.getDay25().hashCode());
		result = 37 * result + (getDay26() == null ? 0 : this.getDay26().hashCode());
		result = 37 * result + (getDay27() == null ? 0 : this.getDay27().hashCode());
		result = 37 * result + (getDay28() == null ? 0 : this.getDay28().hashCode());
		result = 37 * result + (getDay29() == null ? 0 : this.getDay29().hashCode());
		result = 37 * result + (getDay30() == null ? 0 : this.getDay30().hashCode());
		result = 37 * result + (getDay31() == null ? 0 : this.getDay31().hashCode());
		result = 37 * result + (getStatas() == null ? 0 : this.getStatas().hashCode());
		result = 37 * result + (getReasion() == null ? 0 : this.getReasion().hashCode());
		return result;
	}

}
